package pe.edu.upeu.clinicamobil.presentation.theme

import androidx.compose.ui.graphics.Color

// Paleta clínica azul/verde-azulado (teal), distinta del verde de PharmaMobil
// y del morado por defecto de Material.

val ClinicaPrimaryLight = Color(0xFF0B5FA5)
val ClinicaOnPrimaryLight = Color(0xFFFFFFFF)
val ClinicaPrimaryContainerLight = Color(0xFFD3E4FF)
val ClinicaOnPrimaryContainerLight = Color(0xFF001C3A)
val ClinicaSecondaryLight = Color(0xFF0F9C8E)
val ClinicaOnSecondaryLight = Color(0xFFFFFFFF)
val ClinicaSecondaryContainerLight = Color(0xFFB0F1E4)
val ClinicaOnSecondaryContainerLight = Color(0xFF00201B)
val ClinicaTertiaryLight = Color(0xFF8A5300)
val ClinicaOnTertiaryLight = Color(0xFFFFFFFF)
val ClinicaTertiaryContainerLight = Color(0xFFFFDDB3)
val ClinicaOnTertiaryContainerLight = Color(0xFF2B1700)
val ClinicaErrorLight = Color(0xFFBA1A1A)
val ClinicaOnErrorLight = Color(0xFFFFFFFF)
val ClinicaErrorContainerLight = Color(0xFFFFDAD6)
val ClinicaOnErrorContainerLight = Color(0xFF410002)
val ClinicaBackgroundLight = Color(0xFFF9FAFE)
val ClinicaOnBackgroundLight = Color(0xFF1A1C1E)
val ClinicaSurfaceLight = Color(0xFFF9FAFE)
val ClinicaOnSurfaceLight = Color(0xFF1A1C1E)
val ClinicaSurfaceVariantLight = Color(0xFFDFE2EB)
val ClinicaOnSurfaceVariantLight = Color(0xFF43474E)
val ClinicaOutlineLight = Color(0xFF73777F)
val ClinicaOutlineVariantLight = Color(0xFFC3C7CF)
val ClinicaScrimLight = Color(0xFF000000)
val ClinicaInverseSurfaceLight = Color(0xFF2F3033)
val ClinicaInverseOnSurfaceLight = Color(0xFFF1F0F4)
val ClinicaInversePrimaryLight = Color(0xFFA5C8FF)
val ClinicaSurfaceDimLight = Color(0xFFD9DAE0)
val ClinicaSurfaceBrightLight = Color(0xFFF9FAFE)
val ClinicaSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val ClinicaSurfaceContainerLowLight = Color(0xFFF3F4F9)
val ClinicaSurfaceContainerLight = Color(0xFFEDEEF3)
val ClinicaSurfaceContainerHighLight = Color(0xFFE7E8EE)
val ClinicaSurfaceContainerHighestLight = Color(0xFFE2E2E8)

val ClinicaPrimaryDark = Color(0xFFA5C8FF)
val ClinicaOnPrimaryDark = Color(0xFF00325A)
val ClinicaPrimaryContainerDark = Color(0xFF00497F)
val ClinicaOnPrimaryContainerDark = Color(0xFFD3E4FF)
val ClinicaSecondaryDark = Color(0xFF53DBC9)
val ClinicaOnSecondaryDark = Color(0xFF00382F)
val ClinicaSecondaryContainerDark = Color(0xFF005045)
val ClinicaOnSecondaryContainerDark = Color(0xFFB0F1E4)
val ClinicaTertiaryDark = Color(0xFFFFB951)
val ClinicaOnTertiaryDark = Color(0xFF482900)
val ClinicaTertiaryContainerDark = Color(0xFF673D00)
val ClinicaOnTertiaryContainerDark = Color(0xFFFFDDB3)
val ClinicaErrorDark = Color(0xFFFFB4AB)
val ClinicaOnErrorDark = Color(0xFF690005)
val ClinicaErrorContainerDark = Color(0xFF93000A)
val ClinicaOnErrorContainerDark = Color(0xFFFFDAD6)
val ClinicaBackgroundDark = Color(0xFF111318)
val ClinicaOnBackgroundDark = Color(0xFFE2E2E9)
val ClinicaSurfaceDark = Color(0xFF111318)
val ClinicaOnSurfaceDark = Color(0xFFE2E2E9)
val ClinicaSurfaceVariantDark = Color(0xFF43474E)
val ClinicaOnSurfaceVariantDark = Color(0xFFC3C7CF)
val ClinicaOutlineDark = Color(0xFF8D9199)
val ClinicaOutlineVariantDark = Color(0xFF43474E)
val ClinicaScrimDark = Color(0xFF000000)
val ClinicaInverseSurfaceDark = Color(0xFFE2E2E9)
val ClinicaInverseOnSurfaceDark = Color(0xFF2F3033)
val ClinicaInversePrimaryDark = Color(0xFF0B5FA5)
val ClinicaSurfaceDimDark = Color(0xFF111318)
val ClinicaSurfaceBrightDark = Color(0xFF37393E)
val ClinicaSurfaceContainerLowestDark = Color(0xFF0C0E13)
val ClinicaSurfaceContainerLowDark = Color(0xFF191C20)
val ClinicaSurfaceContainerDark = Color(0xFF1D2024)
val ClinicaSurfaceContainerHighDark = Color(0xFF282A2F)
val ClinicaSurfaceContainerHighestDark = Color(0xFF33353A)
